name: Build, Test, and Push container image
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      id: login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      id: build
      run: docker build . --file Dockerfile --tag ${ secrets.DOCKERHUB_USERNAME  }}/flask-app-gitops
    - name: Push the Docker image
      id: push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app-gitops
